apiVersion: batch/v1
kind: Job
metadata:
  name: sleep-10
spec:
  completions: 400
  parallelism: 400
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: sleep1
        image: "alpine:latest"
        command: ["sleep", "5"]
        resources:
          requests:
            cpu: "500m"
            memory: "500M"
