apiVersion: batch/v1
kind: Job
metadata:
  name: SLEEPID
spec:
  template:
    spec:
      containers:
      - name: SLEEPID
        image: "alpine:latest"
        command: ["sleep",  "5"]
        resources:
          requests:
            cpu: "500m"
            memory: "500M"
      restartPolicy: Never
  backoffLimit: 4
