apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: sleep5-2000
  labels:
    app: sleep-5s
    tier: sleep
spec:
  # modify replicas according to your case
  replicas: 1 
  selector:
    matchLabels:
      tier: sleep
  template:
    metadata:
      labels:
        tier: sleep
    spec:
      containers:
      - name: sleep-5s
        image: "alpine:latest"
        command: ["sleep 5"]
        resources:
          requests:
            cpu: "500m"
            memory: "500M"
